name: Get GitHub Badges Trick

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 */6 * * *'

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Trigger Pull Shark & YOLO
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        
        BRANCH_NAME="patch-${{ github.run_id }}-${{ github.run_number }}"
        git checkout -b $BRANCH_NAME
        
        echo "Update: $(date)" >> progress.txt
        git add progress.txt
        git commit -m "Update development progress logs"
        
        # Yahan -f (force push) add kiya hai taake conflict na aaye
        git push origin $BRANCH_NAME -f
        
        gh pr create --title "Merge development logs" --body "Automated update for development logs." --base main --head $BRANCH_NAME
        gh pr merge --merge --delete-branch
